#pragma once
#include "utils.h"
#include "actuators/buttons.h"
#include "sensors/sensor_data_buffer.h"
#include "actuators/display_screen.h"
#include "sensors/multizone_tof_sensor.h"
#include "sensors/imu.h"
#include "sensors/side_tof_manager.h"
#include "networking/serial_queue_manager.h"

void multizone_tof_logger();
void imu_logger();
void side_tofs_logger();
void side_tof_logger();
void color_sensor_logger();
void ir_sensor_logger();
void setup_button_loggers();
void log_motor_rpm();
void display_performance_logger();
